//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifting_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiftingDataBaseEntities1 : DbContext
    {
        public LiftingDataBaseEntities1()
            : base("name=LiftingDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<PasswordStore> PasswordStores { get; set; }
        public virtual DbSet<UserName> UserNames { get; set; }
    }
}
